import Header from "@/components/Header"
import Container from "@/components/std/Container"
import "@/styles/global.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <Container>
          {children}
        </Container>
      </body>
    </html>
  )
}
